version: '3'

services:
  app:
    image: phone-booking/app:latest
    build: .
    ports:
      - "4000:4000"
    environment:
      - MONGODB_PATH=mongodb://mongo:27017/phone-booking
  mongo:
    image: "mongo:3.2.21-jessie"
